services:
  php81:
    build:
      context: ./build
      dockerfile: Dockerfile
    working_dir: "/app"
    volumes:
      - .:/app
      - ./tmp:/tmp/parkrun-scraper
      - ../php-time-source:/php-time-source
